# Generated by Django 3.2.9 on 2021-12-02 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название компании')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('active_now', models.BooleanField(default=True, verbose_name='Активна на сайте')),
                ('company_logo', models.ImageField(blank=True, upload_to='companies')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL, verbose_name='Владелец компании')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Список компаний',
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название студии')),
                ('city', models.CharField(max_length=25, verbose_name='Город')),
                ('address', models.TextField(max_length=200, verbose_name='Адрес')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studios', to='api.company', verbose_name='Лэйбл')),
            ],
            options={
                'verbose_name': 'Студия',
                'verbose_name_plural': 'Список студий',
                'ordering': ('company', 'city', 'name'),
                'unique_together': {('name', 'city', 'address')},
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_recording', models.DateTimeField(verbose_name='Старт записи')),
                ('end_recording', models.DateTimeField(verbose_name='Конец записи')),
                ('duration', models.DurationField(verbose_name='Длительность')),
                ('cost', models.PositiveSmallIntegerField(verbose_name='Стоимость часа записи')),
                ('session_cost', models.PositiveIntegerField(verbose_name='Стоимость сеанса')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='api.studio')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Таблица записи',
            },
        ),
    ]
