# Generated by Django 3.2.9 on 2021-12-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_logo',
            field=models.ImageField(blank=True, upload_to='companies', verbose_name='Логотип'),
        ),
    ]
